### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by Gengar-lab** [xencodes/bombsquad#1]
Some mods to play on original bombsquad please...

**Comment by mxvsh** [comment]
What do you mean?

**Comment by Benefit-Zebra** [comment]
Do you create bombsquad mods ?

**Comment by mxvsh** [comment]
yes

**Comment by Gengar-lab** [comment]
I can't find them. Why?

**Comment by rahulraman0108** [comment]
Write here about mods you want.

**Comment by Gengar-lab** [comment]
Blackhole bomb to play on original bombsquad.

**Comment by rahulraman0108** [comment]
Nice idea, will try to add soon. Thanks for suggestion!

**Comment by Gengar-lab** [comment]
Where is the devxen?

**Comment by rahulraman0108** [comment]
In home.

**Comment by mxvsh** [comment]
@Benefit-Zebra i am here

**Comment by Gengar-lab** [comment]
Wait, are you the devxen?

**Comment by mxvsh** [comment]
@Benefit-Zebra no.. here i am

**Comment by rahulraman0108** [comment]
@TheDevXen I am here

**Comment by Gengar-lab** [comment]
Then who is that the great?

**Comment by mxvsh** [comment]
@Benefit-Zebra he is also a modder

**Comment by rahulraman0108** [comment]
@Benefit-Zebra I am his friend

**Comment by Gengar-lab** [comment]
Ohh

**Comment by mxvsh** [comment]
@Benefit-Zebra here on telegram

**Comment by Gengar-lab** [comment]
Ok

**Comment by mxvsh** [comment]
@Benefit-Zebra join our telegram group

**Comment by rahulraman0108** [comment]
@TheDevXen Link is http://t.me/XensParty

**Comment by Gengar-lab** [comment]
The DevXen can you make Blackhole bomb to play on original bombsquad?

**Comment by rahulraman0108** [comment]
@Benefit-Zebra I can, but will take time

**Comment by Gengar-lab** [comment]
Ok

**Comment by mxvsh** [comment]
@Benefit-Zebra its better to discuss not on GitHub issue page, but here on telegram

**Comment by rahulraman0108** [comment]
@TheDevXen Yeah

**Comment by rahulraman0108** [comment]
@TheDevXen Sorry

**Comment by Benefit-Zebra** [comment]
Sorry I don't have space to download it

**Comment by mxvsh** [comment]
@Benefit-Zebra okkk use web.telegram.org

**Comment by rahulraman0108** [comment]
@TheDevXen Online telegram👍

**Comment by Benefit-Zebra** [comment]
See you later

Bye.

**Comment by rahulraman0108** [comment]
@Benefit-Zebra Same to you
